### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#111]
- [x] make organisation boxes same-sized on the home page
<img width="531" alt="Screen Shot 2022-04-20 at 13 08 33" src="https://user-images.githubusercontent.com/12149023/164217940-be7a93b8-bf7e-4988-ba46-0a943817ae25.png">

- [ ] align buttons width across the app

- [x] fix the way search field and buttons are displayed on the home page - looks messy now
<img width="675" alt="Screen Shot 2022-04-20 at 13 06 00" src="https://user-images.githubusercontent.com/12149023/164217705-8982d746-ddaf-4bfe-9f42-ec5327ee743e.png">

- [ ] align colours across the service, perhaps we could just use Schibted's without add-ons?

**Comment by adrkakol** [comment]
#118 solves tiles height

**Comment by adrkakol** [comment]
#120 and #121 improves layout of buttons on the home page
