### ISSUE TITLE
Possibility to add link to ongoing fund collection

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#113]
It would be great if we could add a possibility to link to ongoing fund collections like zrzutka: https://zrzutka.pl/95khhv for given organisation, apart from displaying the bank account number
<img width="590" alt="Screen Shot 2022-04-22 at 11 20 28" src="https://user-images.githubusercontent.com/12149023/164677275-c264f3be-92e2-4b84-90f9-77cac05ab472.png">

can we adjust on backend for that? @michaldomagalski @adrkakol :)

**Comment by adrkakol** [comment]
@AgaLasyk YES! I can code that on BE and add to FE

**Comment by agnieszkalasyk** [comment]
we could perhaps also hide both (account number/fund collection link) if empty?

**Comment by adrkakol** [comment]
> we could perhaps also hide both (account number/fund collection link) if empty?

I think that it is better to show it  even if it is empty- not much  places right now have the info, but users can see that they can expect it filed in on other places' sites
