### ISSUE TITLE
Display additional info related to Bank Account number 

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#135]
ref. this post https://www.facebook.com/koalicja.otwarty.krakow/posts/131043069510801 we can clearly see that Bank Account number info is frequently followed by more details such as "title of payment" that differs across the organisations, it would be good to provide those informations on our site, next to the Bank Account number

**Comment by michaldomagalski** [comment]
API response ready and released live.
