### ISSUE TITLE
Bug: search field on demands edition not translated

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#158]
Search field and placeholder on the view with demands' list edition are not translated:
<img width="457" alt="Screen Shot 2022-05-03 at 23 57 39" src="https://user-images.githubusercontent.com/12149023/166573462-de283185-2772-4832-be9e-3ce8781ab76f.png">

**Comment by katarzyna-palka** [comment]
Found places are not translated

<img width="1429" alt="Screen Shot 2022-05-05 at 10 50 54" src="https://user-images.githubusercontent.com/104977044/166891527-ea87f1da-97de-438f-9e1c-539604780f72.png">
