### ISSUE TITLE
Add placeId to payload while creating new comment for announcement

### ISSUE THREAD

**Issue by michaldomagalski** [copotrzebne-pl/copotrzebne-frontend#168]
We now have additional column `placeId` in `announcements_comments` table, so we need to send `placeId` in payload while creating new comment.

https://copotrzebne.pl/api/docs/#/announcement-comments/AnnouncementCommentsController_createAnnouncementComment

Important note about announcements features:
- Backend is released both on dev and prod
- Front is released only on dev

**Comment by agnieszkalasyk** [comment]
duplicate of #146 ?

**Comment by michaldomagalski** [comment]
Ah, yes - sorry for that.
