### ISSUE TITLE
Add possibility to set organisation to `inactive/drafted` if there is no collection for a longer time

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#180]
For the sake of organisations/places that take part in some occasional collections yet for the majority of time do not have any ongoing collection admins should be able to set their state to `inactive/drafted` - with that, we could still have them ready to put up, if there is a new ad-hoc collection, yet they will not be visible on the site. We should also remove them from map.
Anything we need to add on backend to accommodate this or is it ready to go? @michaldomagalski @adrkakol

**Comment by michaldomagalski** [comment]
@agnieszkalasyk with current logic deactivated places keep their demands intact and admin can still modify them, so I think that's everything what we need here, hence - we're ready to go 😊
