### ISSUE TITLE
`Public announcements` simplified form

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#181]
We could consider removing `title` and `contact` info from the `public announcements` form, it's enough to have the "contents" as we want to have a simple feed with the announcements on the organisation homepage and copotrzebne home page
<img width="794" alt="Screen Shot 2022-05-08 at 15 10 33" src="https://user-images.githubusercontent.com/12149023/167297906-df43d651-3d32-4c5e-b906-cbcde4c9c3e1.png">
.

**Comment by michaldomagalski** [comment]
@agnieszkalasyk should we keep those columns in db "just in case" or completely remove those props for public announcements?
