### ISSUE TITLE
Updates to demands list

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#61]
it would be great if we add following functionalities to demands list:
- possibility to edit already added item from demands list (change priority or comment) - currently we can only delete given demand
- preview of comment on the demand tile (if you add given item twice you can't see details/comments of each and it's hard p.ex. to delete the wrong one)
<img width="462" alt="Screen Shot 2022-04-01 at 16 29 17" src="https://user-images.githubusercontent.com/12149023/161284004-ed2bad89-2886-410a-b04d-34c5badf217f.png">

- mark items already on the list when going from existing demands list to demands edition/adding new demands
<img width="485" alt="Screen Shot 2022-04-01 at 16 29 27" src="https://user-images.githubusercontent.com/12149023/161284042-43902456-8c70-4acd-9d75-199aea8b7771.png">

**Comment by baqui** [comment]
Resolved in: https://github.com/copotrzebne-pl/copotrzebne-frontend/pull/74
