### ISSUE TITLE
Search bug: next item marked as selected

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#67]
Steps to reproduce:
- log in as tester or org manager
- go into "add/edit demands"
- use search field to browse "Słodycze"
<img width="535" alt="Screen Shot 2022-04-02 at 10 05 42" src="https://user-images.githubusercontent.com/12149023/161373419-e9486d60-bb2b-433b-b848-02120be80d5c.png">

- select item, add comment, save&add to the list
<img width="505" alt="Screen Shot 2022-04-02 at 09 52 01" src="https://user-images.githubusercontent.com/12149023/161373291-495ac4e8-26bc-4716-8eef-9cd7c2b92599.png">
<img width="492" alt="Screen Shot 2022-04-02 at 09 52 07" src="https://user-images.githubusercontent.com/12149023/161373305-efe0cbc5-2717-49bf-b86a-eaa402e2a4c8.png">

- stay where you are, do not refresh page - put another query in the search box p.ex. "Cukier"; btw if there are more supplies matching the query only the first one that matches is selected (check with "Mleko")
<img width="581" alt="Screen Shot 2022-04-02 at 09 52 13" src="https://user-images.githubusercontent.com/12149023/161373316-cd246e13-833b-41d4-9726-181e7f5054d1.png">

- it looks marked/selected although it has not been
- open item details - see comment from "Słodycze" copied into "Cukier"
<img width="492" alt="Screen Shot 2022-04-02 at 09 52 18" src="https://user-images.githubusercontent.com/12149023/161373326-05a64798-4dfa-44e9-9ffa-85c2abe0d6f9.png">

- do not add item, change query again to something else like "Pomidory" - no bug

**Comment by baqui** [comment]
Resolved in: https://github.com/copotrzebne-pl/copotrzebne-frontend/pull/70
