### ISSUE TITLE
Small tweaks to UI - button text, category headers, finish collection button

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#77]
It would be nice to adjust a few button labels and perhaps change category headers not to look like input fields.
Changes to the button text:
- when updating the demand properties like priority or comments the button should say "save changes" not "add demand to the list"
- when creating new org the button linking to form with org data should say "add new org" not "edit the org data"
- change text from "finish collection" to "remove all products (at least until we do not have collections instance), this button should perhaps be more visible?

**Comment by vizZ** [comment]
- in `Organisation Details Page`:
     - [ ] `Product List` `Headers`' styling is off, it looks like some kind of `input`
     - [ ] Font colour in the `Organisation Details` (top header) is grey on light grey background, this is hard to read
