### ISSUE TITLE
Changing the comment/links structure 

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#80]
We should add links as a separate organisation property, not related to `comment`. We should have fields to provide the following: 
- link to homepage
- link to facebook
- sign-up for volunteers
- collection page/fundraising link

**Comment by agnieszkalasyk** [comment]
@michaldomagalski please let me know when it is ready on backend :)

**Comment by michaldomagalski** [comment]
Backend ready :)
https://github.com/copotrzebne-pl/copotrzebne-api/pull/130
