### ISSUE TITLE
Add possibility to confirm current demands and bump "last modified at" with one click

### ISSUE THREAD

**Issue by agnieszkalasyk** [copotrzebne-pl/copotrzebne-frontend#85]
Currently we are sorting the organisations by "last modified at", showing the latest first, we are also displaying the date of the demands list modification, which results in pushing the organisations without changes in the current demands toward the end of the list, some users might also think the needs of given organisation aren't "current". 
To resolve it, we should add an a button (or another way) to confirm that the demands are current and with that click bump the "last updated at" date.
@martynabrk perhaps you should suggest a solution here? :) 
This will also change the way how we define "last updated at" since currently is the date of latest update of any demand on this organisation's list - any thoughts on that @michaldomagalski ?

**Comment by michaldomagalski** [comment]
We have a backend issue: https://github.com/copotrzebne-pl/copotrzebne-api/issues/95
